apiVersion: apps/v1
kind: Deployment
metadata:
    name: frontend
    namespace: {{ .Values.namespace }}
    labels:
        app: frontend
spec:
    replicas: {{ .Values.frontend.replicas }}
    strategy:
        type: RollingUpdate
        rollingUpdate:
            maxSurge: 1
            maxUnavailable: 0
    selector:
        matchLabels:
            app: frontend
    template:
        metadata:
            labels:
                app: frontend
        spec:
            imagePullSecrets:
                - name: ecr-pull-secret
            containers:
                - name: frontend
                  image: '{{ .Values.frontend.image.repository }}:{{ .Values.frontend.image.tag }}'
                  imagePullPolicy: '{{ .Values.frontend.image.pullPolicy }}'
                  ports:
                      - containerPort: {{ .Values.frontend.port }}
                  readinessProbe:
                      httpGet:
                          path: {{ .Values.frontend.probes.path }}
                          port: {{ .Values.frontend.port }}
                      initialDelaySeconds: 5
                      periodSeconds: 5
                      timeoutSeconds: 2
                      failureThreshold: 6
                  livenessProbe:
                      httpGet:
                          path: {{ .Values.frontend.probes.path }}
                          port: {{ .Values.frontend.port }}
                      initialDelaySeconds: 15
                      periodSeconds: 10
                      timeoutSeconds: 2
                  resources:
                      requests:
                          cpu: {{ .Values.frontend.resources.requests.cpu }}
                          memory: {{ .Values.frontend.resources.requests.memory }}
                      limits:
                          cpu: {{ .Values.frontend.resources.limits.cpu }}
                          memory: {{ .Values.frontend.resources.limits.memory }}
