{{- if .Values.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: today-stock-web
  namespace: {{ .Values.namespace }}
  annotations:
    kubernetes.io/ingress.class: "nginx"
    {% comment %} cert-manager.io/cluster-issuer: letsencrypt
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true" {% endcomment %}
spec:
  ingressClassName: nginx
  {% comment %} tls:
    - hosts:
        - {{ .Values.ingress.host}}
      secretName: todaystock-tls {% endcomment %}
  rules:
    {% comment %} - host: {{ .Values.ingress.host }} {% endcomment %}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: frontend
                port:
                  number: 80
          - path: /kafka
            pathType: Prefix
            backend:
              service:
                name: kafka-ui
                port:
                  number: 8080
          - path: /airflow
            pathType: Prefix
            backend:
              service:
                name: airflow-webserver
                port:
                  number: 8080
{{- end }}
