{{- if .Values.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: today-stock
  namespace: {{ .Values.namespace }}
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/use-regex: "true"
    nginx.ingress.kubernetes.io/rewrite-target: "/$1"
spec:
  ingressClassName: nginx
  rules:
    - {{- if .Values.ingress.host }}
      host: {{ .Values.ingress.host }}
      {{- end }}
      http:
        paths:
          # /api, /api/*  → backend ("/api" 접두어 제거)
          - path: /api/?(.*)
            pathType: ImplementationSpecific
            backend:
              service:
                name: backend
                port:
                  number: 8080

          # /kafka, /kafka/* → kafka-ui ("/kafka" 접두어 제거)
          - path: /kafka/?(.*)
            pathType: ImplementationSpecific
            backend:
              service:
                name: kafka-ui
                port:
                  number: 8080

          # /airflow, /airflow/* → airflow-webserver ("/airflow" 접두어 제거)
          - path: /airflow/?(.*)
            pathType: ImplementationSpecific
            backend:
              service:
                name: airflow-webserver
                port:
                  number: 8080

          # 그 외 전부 프런트(정적파일/SPA 라우팅 그대로 전달, 리라이트 없음)
          - path: /(.*)
            pathType: ImplementationSpecific
            backend:
              service:
                name: frontend
                port:
                  number: 80
{{- end }}
