{{- if .Values.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: today-stock-airflow-webserver
  namespace: {{ .Values.namespace }}
spec:
  ingressClassName: nginx
  rules:
    - http:
        paths:
          - path: /airflow
            pathType: Prefix
            backend:
              service:
                name: airflow-webserver
                port:
                  number: 8080
{{- end }}